# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81d19bb7bc3eaf78c70278be0fec28b173e49cae985936e94d564bae454893a0c51b709c9b878ea9ffc64efb78d0e4c985a97ce0810d5ff103b04c9b2c3efc32

test:
  secret_key_base: 548c3d750d77a6bc7659694ff439d63bfbf6bc950703b364aaf1d63f176bc4430c731a13bff5d7f02721a063f38e0aafc2e0d1c8773bbbc4bf7619f3ed7f3b87

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
